SELECT
    pm1.meta_key,
    MAX(CASE WHEN pm1.post_id = 18524 THEN pm1.meta_value END) as DUPLICADO_SI_APARECE,
    MAX(CASE WHEN pm1.post_id = 9559 THEN pm1.meta_value END) as ORIGINAL_NO_APARECE
FROM wp_postmeta pm1
WHERE pm1.post_id IN (18524, 9559)
GROUP BY pm1.meta_key
HAVING DUPLICADO_SI_APARECE != ORIGINAL_NO_APARECE
    OR DUPLICADO_SI_APARECE IS NULL
    OR ORIGINAL_NO_APARECE IS NULL
ORDER BY pm1.meta_key;
